### PR TITLE
Typescript Migration

### PR DESCRIPTION
**Pull request by chris-smith**
Initial work to migrate code base to typescript. Everything compiles and tests work. No type definitions from message generation yet - probably a future pull request. Probably needs another pass before merging.

My current thoughts are to head towards a 4.0 release from here focused on
- Typescript support
- Replace bn.js with BigInt
This will drop support for older Node.js versions.

### CODE REVIEW

**Comment by chris-smith** [comment]
I'm going to close this PR and leave the branch up to work out of while this is still in progress.

**Comment by alexytsu** [comment]
Hi @chris-smith,

We're currently working on developing a custom typings file in order to use rosnodejs within our codebase. However it seems like this work will be made redundant when [this branch](https://github.com/RethinkRobotics-opensource/rosnodejs/tree/typescriptSupport) lands. 

Is migrating the codebase to TypeScript currently under progress or something we could contribute to?

**Comment by chris-smith** [comment]
Hi Alex

It's still under progress. I haven't had much time lately to keep working on it. I'm happy for help if you have time.

I haven't actually tried using the library from typescript yet so I assume there are issues there, though I believe it builds and tests pass. The other thing to figure out is how to generate type files for ros messages and include them. I mostly anticipate this will only work with `rosnodejs` generated messages rather than `gennodejs` ones.

I started a bit of work on that [here](https://github.com/csmith-rtr/rosnodejs/commit/e4a91dfcf780da5beb7bb0c463a0ec5d9b25359e) where I was having issues getting the typings for the messages to work.

**Comment by alexytsu** [comment]
Thanks for the context Chris,

I'll admit I still need to acquaint myself more with the codebase before I can offer any meaningful contributions or insights. I do intend to invest some time into this when the new year rolls around for the purpose of progressing adoption of `rosnodejs` into our TypeScript codebase.  

Thanks for the link to your current progress. I'll begin with a dig around the message type generation problem when I have some more time/understanding.

**Pull request closed without merging**
