### PR TITLE
Updated arguments of actionClientInterface to fix getActionClient

### LINKED ISSUE #86: getActionClient broken in 2.2.0
See https://github.com/RethinkRobotics-opensource/rosnodejs/pull/65/files#r173348798.

To reproduce, just run the example shown in the code:
```js
      let ac = rosNode.getActionClient({
        type: "turtle_actionlib/ShapeAction",
        actionServer: "/turtle_shape"
      });
```

Which will result in an error like this:
```
/home/cfritz/work/rosjs/src/lib/NodeHandle.js:210
      throw new Error(`Unable to create action client ${actionServer} without type - got ${type}`);
      ^

Error: Unable to create action client [object Object] without type - got undefined
    at NodeHandle.actionClientInterface (/home/cfritz/work/rosjs/src/lib/NodeHandle.js:210:13)
    at Object.getActionClient (/home/cfritz/work/rosjs/src/index.js:334:20)
    at Timeout._onTimeout (/home/cfritz/work/rosjs/src/examples/turtle.js:82:26)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

It's easy to fix. I'll create a PR.

### PR DESCRIPTION
**Pull request by chfritz**
Fixes #86.

### CODE REVIEW

**Comment by chris-smith** [comment]
I'd rather leave the signature of the new `NodeHandle.actionClientInterface()` alone since it mirrors what exists for subscribers, publishers, services, and actionServiceInterface.

Longer term, I also think it'd be best to deprecate `rosnodejs.getActionClient()` since it doesn't line up with the general pattern of ROS communication (subscribing, getting params, etc) happening through the `NodeHandle`. We should definitely fix #86 and continue supporting it for now though.

**Comment by chfritz** [comment]
ok, sounds good to me. I'll change the PR to modify `rosnodejs.getActionClient()` instead of `NodeHandle.actionClientInterface()`.

**Comment by chfritz** [comment]
Done.

**Review by chris-smith — APPROVED** [review]
Looks great! Thanks!

**Pull request merged**
