### PR TITLE
Issue#6 generate message handlers automatically

### LINKED ISSUE #6: Create message classes on the fly
Hey guys,

rosnodejs had this nice ability to find and load .msg files for the used message types and generate the appropriate js class definitions on the fly -- and I extended that to .srv files, too. This essentially brings what you currently seem to have in genjs into the library itself, i.e., it saves a compilation step. I was thinking of porting that functionality to rosjs. Are you open to pull requests like that?

In general I'd like to contribute to rosjs if I can. I was just pointed to this project by Brandon Alexander, who wrote rosnodejs. I was going to complete that project, but it seems that you guys are way ahead of me and already rewrote the whole thing in super clean ES6 :-)

Anyhow, please let me know how you feel about contributions in general and this particular feature in particular.

### PR DESCRIPTION
**Pull request by chfritz**
Fixes #6.

This PR ports the message handler generation from @baalexander's rosnodejs, extended for services in https://github.com/chfritz/rosnodejs, to this repo. The newly added example2.js shows how to run this.

As a reminder, the main benefit of this is that it doesn't require gennodejs to have already generated javascript class definitions. Instead these classes are generated on demand (and in javascript itself). In the current implementation such demand is expressed using the `rosnodejs.use(messageTypes, serviceTypes, callback)` function (see example2.js).

Currently the message generator searches the ROS_PACKAGE_PATH to find the .msg and .srv files required to generate the classes. In the future it might make sense to also search through the current working directory, to allow applications where ROS isn't even installed/setup on the machine where this is run, and instead enable users to just keep copies of those .msg and .srv files in their repo.

### CODE REVIEW

**Comment by chris-smith** [comment]
Awesome! I've only managed to look at this quickly but haven't seen any issues so far. I should have time tomorrow to get into it a bit more.

**Comment by IanTheEngineer** [comment]
Wow, this is really cool. Thanks @chfritz! While we are reviewing, could you rebase your PR to clean up the work in progress commits? Perhaps 3 commits: one for your messages work, one for services, and one for the examples? That's just an example, totally up to you how you'd like to organize it.

**Comment by chfritz** [comment]
Sounds good. Will do.

**Comment by chfritz** [comment]
OK, done. This should be a little cleaner in the history.

**Comment by chris-smith** [comment]
This looks good to me. I don't see any reason not to merge it as is - its entirely new functionality and barely touches the existing code. Ran existing example and tests. I tested out the new example with some more complicated messages too without issues. @IanTheEngineer?

**Comment by IanTheEngineer** [comment]
This looks really good, and I am inclined to merge as-is. We should work to unify the API between the on the fly message gen, and the pre-generated messages. Users would then switch between the two by setting a flag through a function call.

**Comment by chfritz** [comment]
@IanTheEngineer agreed! I created a ticket for that.

**Pull request merged**
